apiVersion: 1
policies:
    - orgId: 1
      receiver: Drift Guardian Alerts Telegram
      group_by:
        - grafana_folder
        - alertname
      routes:
        - receiver: Drift Guardian Alerts Telegram
          object_matchers:
            - - service
              - =
              - drift_guardian
            - - severity
              - =
              - critical
          group_wait: 10s
          group_interval: 1m
          repeat_interval: 1m
        - receiver: Drift Guardian Alerts Telegram
          object_matchers:
            - - service
              - =
              - drift_guardian
            - - severity
              - =
              - warning
          active_time_intervals:
            - working-hours-morning
          group_wait: 10s
          group_interval: 1m
          repeat_interval: 1m
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
